import type { RiskEvent } from './types'

/**
 * Supabase 미연결 시 쓰는 샘플 데이터.
 *
 * 내용은 wiki/spec/business-rules.md "계산 예시"의 사례를 그대로 옮겨
 * severity 판정이 화면에서 어떻게 보이는지 확인할 수 있게 했다.
 *
 * ⚠️ event_id의 유형 코드는 BH(Bank Holiday)·DB(Driving Ban)만 실제 확인분이다
 *    (data-model.md). ST·WX·IN은 이 샘플에서 임의로 정한 것이며 실제 규칙이 아니다.
 */

const now = new Date().toISOString()
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString()

export const SAMPLE_EVENTS: RiskEvent[] = [
  {
    event_id: 'DE-DB-20260815-BY',
    event_type: 'Driving Ban',
    country: 'Germany',
    region: 'Bavaria',
    date_start: '2026-08-15',
    date_end: '2026-08-16',
    time_start: '08:00',
    time_end: '22:00',
    event_name: 'Assumption Day driving ban',
    summary: '7.5t 초과 트럭 전면 운행금지. 전날 일요일 금지와 연속.',
    transport_mode: 'road',
    severity: 5,
    severity_reason: '주간 금지 13h(>5h)=4점, 일요일과 2일 연속 +1 → 5',
    status: 'active',
    source_url: 'https://trafficban.com/de',
    verified: 'yes',
    upd_dtm: hoursAgo(2),
  },
  {
    event_id: 'FR-ST-20260812-ALL',
    event_type: 'Strike',
    country: 'France',
    region: null,
    date_start: '2026-08-12',
    date_end: '2026-08-13',
    time_start: null,
    time_end: null,
    event_name: 'SNCF national rail strike',
    summary: '전국 철도 파업 2일. 화물 운송 전면 지연 예상.',
    transport_mode: 'rail',
    severity: 4,
    severity_reason: '물류 직접 부문 3점 + 전국 규모 +1 → 4',
    status: 'active',
    source_url: 'https://www.sncf.com',
    verified: 'yes',
    upd_dtm: hoursAgo(5),
  },
  {
    event_id: 'PL-WX-20260810-ALL',
    event_type: 'Weather',
    country: 'Poland',
    region: 'Mazowieckie',
    date_start: '2026-08-10',
    date_end: '2026-08-11',
    time_start: null,
    time_end: null,
    event_name: 'Orange warning — heavy rain',
    summary: 'Meteoalarm Orange 경보. 도로·철도 지연 가능.',
    transport_mode: 'road,rail',
    severity: 3,
    severity_reason: 'Meteoalarm Orange 직접 매핑 → 3',
    status: 'active',
    source_url: 'https://feeds.meteoalarm.org',
    verified: 'yes',
    upd_dtm: hoursAgo(1),
  },
  {
    event_id: 'IT-ST-20260814-LOM',
    event_type: 'Strike',
    country: 'Italy',
    region: 'Lombardy',
    date_start: '2026-08-14',
    date_end: '2026-08-14',
    time_start: '06:00',
    time_end: '14:00',
    event_name: 'Single logistics hub strike (80 workers)',
    summary: '단일 물류센터 80명 파업 1일.',
    transport_mode: 'road',
    severity: 2,
    severity_reason: '물류 직접 3점 − 소규모·단일사업장 1 → 2',
    status: 'active',
    source_url: 'https://example.it/news',
    verified: 'no',
    upd_dtm: hoursAgo(30),
  },
  {
    event_id: 'SK-BH-20260815-ALL',
    event_type: 'Bank Holiday',
    country: 'Slovakia',
    region: null,
    date_start: '2026-08-15',
    date_end: '2026-08-15',
    time_start: null,
    time_end: null,
    event_name: 'Assumption of Mary',
    summary: '공휴일. 고객 창고 언로딩 불가 가능 → 트럭 조기 도착 시 대기 발생 가능.',
    transport_mode: 'road',
    severity: 1,
    severity_reason: '공휴일 기본 1점. 운행금지 교차 확인 결과 없음.',
    status: 'active',
    source_url: 'https://date.nager.at/api/v3/PublicHolidays',
    verified: 'yes',
    upd_dtm: hoursAgo(72),
  },
  {
    event_id: 'AT-BH-20260815-ALL',
    event_type: 'Bank Holiday',
    country: 'Austria',
    region: null,
    date_start: '2026-08-15',
    date_end: '2026-08-15',
    time_start: null,
    time_end: null,
    event_name: 'Mariä Himmelfahrt',
    summary: '공휴일. 운행금지 자동 발동 국가 — 교차 확인 필요.',
    transport_mode: 'road',
    severity: 1,
    severity_reason: '공휴일 기본 1점',
    status: 'active',
    source_url: 'https://date.nager.at/api/v3/PublicHolidays',
    verified: 'yes',
    upd_dtm: hoursAgo(72),
  },
  {
    event_id: 'BE-BH-20260815-ALL',
    event_type: 'Bank Holiday',
    country: 'Belgium',
    region: null,
    date_start: '2026-08-15',
    date_end: '2026-08-15',
    time_start: null,
    time_end: null,
    event_name: 'Assumption Day',
    summary: '공휴일이나 운행 제한 없음 → 영향 낮음.',
    transport_mode: 'road',
    severity: 1,
    severity_reason: '공휴일 기본 1점. 운행금지 없음.',
    status: 'active',
    source_url: 'https://date.nager.at/api/v3/PublicHolidays',
    verified: 'yes',
    upd_dtm: hoursAgo(72),
  },
  {
    event_id: 'NL-WX-20260818-ALL',
    event_type: 'Weather',
    country: 'Netherlands',
    region: null,
    date_start: '2026-08-18',
    date_end: '2026-08-20',
    time_start: null,
    time_end: null,
    event_name: 'Yellow warning — strong wind',
    summary: '강풍 주의보. 항공·해상 영향.',
    transport_mode: 'air,sea',
    severity: 2,
    severity_reason: 'Meteoalarm Yellow 직접 매핑 → 2',
    status: 'active',
    source_url: 'https://feeds.meteoalarm.org',
    verified: 'yes',
    upd_dtm: hoursAgo(4),
  },
  {
    event_id: 'ES-ST-20260820-CAT',
    event_type: 'Strike',
    country: 'Spain',
    region: 'Catalonia',
    date_start: '2026-08-20',
    date_end: '2026-08-24',
    time_start: null,
    time_end: null,
    event_name: 'Barcelona port workers strike',
    summary: '항만 노동자 파업 5일. 컨테이너 하역 중단.',
    transport_mode: 'sea',
    severity: 4,
    severity_reason: '물류 직접(항만) 3점 + 기간 3일 이상 +1 → 4',
    status: 'active',
    source_url: 'https://example.es/port',
    verified: 'failed',
    upd_dtm: hoursAgo(9),
  },
  {
    event_id: 'CZ-DB-20260823-ALL',
    event_type: 'Driving Ban',
    country: 'Czechia',
    region: null,
    date_start: '2026-08-23',
    date_end: '2026-08-23',
    time_start: '13:00',
    time_end: '22:00',
    event_name: 'Sunday truck restriction',
    summary: '일요일 트럭 운행 제한.',
    transport_mode: 'road',
    severity: 1,
    severity_reason: '일요일 금지는 상시 규정 → 1점(정보성)',
    status: 'active',
    source_url: 'https://trafficban.com/cz',
    verified: 'yes',
    upd_dtm: hoursAgo(48),
  },
  {
    event_id: 'HU-IN-20260819-ALL',
    event_type: 'Incident',
    country: 'Hungary',
    region: 'Budapest',
    date_start: '2026-08-19',
    date_end: '2026-08-19',
    time_start: '05:30',
    time_end: null,
    event_name: 'M1 motorway multi-vehicle collision',
    summary: 'M1 고속도로 다중 추돌. 서행 구간 발생.',
    transport_mode: 'road',
    severity: 3,
    severity_reason: '[미확정] Incident severity 판정 규칙이 아직 없다',
    status: 'active',
    source_url: 'https://example.hu/news',
    verified: 'no',
    upd_dtm: hoursAgo(6),
  },
  {
    event_id: 'FR-DB-20260809-ALL',
    event_type: 'Driving Ban',
    country: 'France',
    region: null,
    date_start: '2026-08-09',
    date_end: '2026-08-09',
    time_start: '07:00',
    time_end: '19:00',
    event_name: 'Summer weekend truck ban',
    summary: '하계 주말 대형 트럭 운행금지.',
    transport_mode: 'road',
    severity: 4,
    severity_reason: '주간 금지 12h(>5h) → 4',
    status: 'active',
    source_url: 'https://trafficban.com/fr',
    verified: 'yes',
    upd_dtm: now,
  },
  {
    event_id: 'RO-WX-20260826-ALL',
    event_type: 'Weather',
    country: 'Romania',
    region: null,
    date_start: '2026-08-26',
    date_end: '2026-08-27',
    time_start: null,
    time_end: null,
    event_name: 'Red warning — flooding',
    summary: '홍수 적색 경보. 도로·철도 통제 가능.',
    transport_mode: 'road,rail',
    severity: 4,
    severity_reason: 'Meteoalarm Red 직접 매핑 → 4',
    status: 'active',
    source_url: 'https://feeds.meteoalarm.org',
    verified: 'yes',
    upd_dtm: hoursAgo(3),
  },
  {
    event_id: 'DE-DB-20260830-ALL',
    event_type: 'Driving Ban',
    country: 'Germany',
    region: null,
    date_start: '2026-08-30',
    date_end: '2026-08-30',
    time_start: '00:00',
    time_end: '22:00',
    event_name: 'Sunday driving ban',
    summary: '일요일 트럭 운행금지 (상시 규정).',
    transport_mode: 'road',
    severity: 1,
    severity_reason: '일요일 금지 → 1점(정보성)',
    status: 'active',
    source_url: 'https://trafficban.com/de',
    verified: 'yes',
    upd_dtm: hoursAgo(96),
  },
]
